[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capstone_stealth_swap = "AgpxpxaZ7cu744XZd1URa62jW9okzvXNMpF6nmED4Bnt"

[programs.devnet]
capstone_stealth_swap = "AgpxpxaZ7cu744XZd1URa62jW9okzvXNMpF6nmED4Bnt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
